2024-06-16 22:44:27 | INFO: 0) Unpack information from JSON
2024-06-16 22:44:27 | INFO: 1) Instantiate and Configure Tool
2024-06-16 22:44:27 | INFO: 2) Run Tool

-- Input data:
{}

-- Arguments:
{'execution': '/shared_data/userdata/user_1/run000', 'project': 'example', 'tool': 'flcoore', 'node_list': 'BSC'}

-- CWD:
/shared_data/userdata/user_1/run000

-- Expected output is:
my_demo_outfile.txt
Obtained token for demo user: ('test@bsc.es',)
CACACACAASCACAC
2024-06-16 22:44:27 | PROGRESS: Triggering tool 'flcore' in nodes '['BSC', 'UCLH', 'UCLH']'
2024-06-16 22:44:27 | DEBUG: 	-- FedManager URL = https://fl.bsc.es/flmanager/API/v1/tools/job/flcore?nodes=BSC,UCLH,UCLH
{'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoc1d1b1g3YTI2VENuZFh2MzBDTjFocDB2eEdxcmMyUnB6SlFxRFpQTGx3In0.eyJleHAiOjE3MTg1ODE0NjcsImlhdCI6MTcxODU3Nzg2NywianRpIjoiYmM5MWM4NmItNDgyNC00YmViLWIxNWUtOTg2MTFmM2JjOWNmIiwiaXNzIjoiaHR0cHM6Ly9pbmIuYnNjLmVzL2F1dGgvcmVhbG1zL2RhdGF0b29sczRoZWFydCIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIxZTk4OThhMi02ZTI3LTQ5MDEtODA4MC03MzQ3NjM4MDg2NGMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmbF9tYW5hZ2VyX2FwaSIsInNlc3Npb25fc3RhdGUiOiI4OGNjNGI4MC1hZjEyLTQxMjAtYTE3MC1jYjZjYmE2OGYyZWUiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1kYXRhdG9vbHM0aGVhcnQiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiODhjYzRiODAtYWYxMi00MTIwLWExNzAtY2I2Y2JhNjhmMmVlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiSm9obiBTbWl0aCIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3RAYnNjLmVzIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IlNtaXRoIiwiZW1haWwiOiJ0ZXN0QGJzYy5lcyJ9.fkZ_NPoev2Ek-NQ-_7cmEjJ_15gJIfUY5Ycn3HcpXqphdfPy0vmnqOqObQzc7AA9bIlqCVaBrCxkaXKnkV4KoNXuZuauyI37GCZppkuYQrGygTrQyjk5xQ4fsfjsS6qXRAEWC20dASqGsDPBEEiyfCxTMOt-_idfUy1kQP4uanA3FXEuGOcmymdiJ5cvZTtVqz_sIlc6t2gQAHalfKNgIr5NUQ6_q6foKhRFqdnpsu_VoyomUPnZ7hEQFjgAygp1mNv-AkGdf8NnMP-fd0fTG_C7zaUXG3qBA9yWbmlu6C3gyy65wWIE2nOhC8BJeom1EC-5M0ljxU_U2shJ1EEMOg', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
curl -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoc1d1b1g3YTI2VENuZFh2MzBDTjFocDB2eEdxcmMyUnB6SlFxRFpQTGx3In0.eyJleHAiOjE3MTg1ODE0NjcsImlhdCI6MTcxODU3Nzg2NywianRpIjoiYmM5MWM4NmItNDgyNC00YmViLWIxNWUtOTg2MTFmM2JjOWNmIiwiaXNzIjoiaHR0cHM6Ly9pbmIuYnNjLmVzL2F1dGgvcmVhbG1zL2RhdGF0b29sczRoZWFydCIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIxZTk4OThhMi02ZTI3LTQ5MDEtODA4MC03MzQ3NjM4MDg2NGMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmbF9tYW5hZ2VyX2FwaSIsInNlc3Npb25fc3RhdGUiOiI4OGNjNGI4MC1hZjEyLTQxMjAtYTE3MC1jYjZjYmE2OGYyZWUiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1kYXRhdG9vbHM0aGVhcnQiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiODhjYzRiODAtYWYxMi00MTIwLWExNzAtY2I2Y2JhNjhmMmVlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiSm9obiBTbWl0aCIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3RAYnNjLmVzIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IlNtaXRoIiwiZW1haWwiOiJ0ZXN0QGJzYy5lcyJ9.fkZ_NPoev2Ek-NQ-_7cmEjJ_15gJIfUY5Ycn3HcpXqphdfPy0vmnqOqObQzc7AA9bIlqCVaBrCxkaXKnkV4KoNXuZuauyI37GCZppkuYQrGygTrQyjk5xQ4fsfjsS6qXRAEWC20dASqGsDPBEEiyfCxTMOt-_idfUy1kQP4uanA3FXEuGOcmymdiJ5cvZTtVqz_sIlc6t2gQAHalfKNgIr5NUQ6_q6foKhRFqdnpsu_VoyomUPnZ7hEQFjgAygp1mNv-AkGdf8NnMP-fd0fTG_C7zaUXG3qBA9yWbmlu6C3gyy65wWIE2nOhC8BJeom1EC-5M0ljxU_U2shJ1EEMOg' 'https://fl.bsc.es/flmanager/API/v1/tools/job/flcore?nodes=BSC,UCLH,UCLH'
2024-06-16 22:45:16 | ERROR: The execution failed. See logs.
2024-06-16 22:45:16 | FATAL: The execution failed. See logs.
2024-06-16 22:45:16 | ERROR: <myTool> tool wasn't executed successfully. ERROR: The execution failed. See logs..
2024-06-16 22:45:16 | ERROR: <myTool> tool wasn't successfully executed. ERROR: <myTool> tool wasn't executed successfully. ERROR: The execution failed. See logs...
Traceback (most recent call last):
  File "/home/vre_template_tool/tool/VRE_Tool.py", line 192, in run_my_demo_pipeline
    result = pipeline.second_demonstrator(token, node_list, tool_name)
  File "/home/vre_template_tool/tool/eucaim_demonstrator.py", line 111, in second_demonstrator
    step_one = execute_tool( token, node_list, tool )
  File "/home/vre_template_tool/tool/eucaim_demonstrator.py", line 86, in execute_tool
    response_data = requests.get ( url, headers = headers )
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vre_template_tool/tool/VRE_Tool.py", line 99, in run
    self.run_my_demo_pipeline(input_files,output_file_path)
  File "/home/vre_template_tool/tool/VRE_Tool.py", line 204, in run_my_demo_pipeline
    raise Exception(errstr)
Exception: The execution failed. See logs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vre_template_tool/VRE_RUNNER.py", line 64, in run
    tt_files, tt_meta = tt_handle.run(input_files, input_metadata, output_files, output_metadata)
  File "/home/vre_template_tool/tool/VRE_Tool.py", line 118, in run
    raise Exception(errstr)
Exception: The execution failed. See logs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vre_template_tool/VRE_RUNNER.py", line 91, in main_wrapper
    result = app.launch(Wrapper, config_path, in_metadata_path, out_metadata_path)
  File "/usr/local/lib/python3.10/dist-packages/apps/jsonapp.py", line 135, in launch
    output_files, output_metadata = super(JSONApp, self).launch(
  File "/usr/local/lib/python3.10/dist-packages/basic_modules/app.py", line 117, in launch
    output_files, output_metadata = tool_instance.run(input_files,
  File "/home/vre_template_tool/VRE_RUNNER.py", line 70, in run
    raise Exception(errstr)
Exception: <myTool> tool wasn't executed successfully. ERROR: The execution failed. See logs..

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vre_template_tool/VRE_RUNNER.py", line 117, in <module>
    RESULTS = main_wrapper(CONFIG, IN_METADATA, OUT_METADATA)
  File "/home/vre_template_tool/VRE_RUNNER.py", line 98, in main_wrapper
    raise Exception(errstr)
Exception: <myTool> tool wasn't successfully executed. ERROR: <myTool> tool wasn't executed successfully. ERROR: The execution failed. See logs...
